services:
  - type: web
    name: twitch-chatgpt-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: sk-enbJYK-KFwVBOb1Zpw3S5wQAa9jzevgmzFA_ZxFZjhT3BlbkFJp7f1Anub93unQVoDpFl3DQwwyDkUF0mGsnVWSnmCEA
      - key: CHANNELS
        value: BraiNext
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "3"
      - key: MODEL_NAME
        value: "gpt-3.5-turbo"
      - key: COMMAND_NAME
        value: "!gpt"
      - key: TWITCH_USER  # https://dev.twitch.tv/console
        value: "BrainBot"
      - key: TWITCH_AUTH  # https://twitchapps.com/tmi/
        value: "oauth:5r95uvj5fh5hcgl8fugv3oqlndzbeh"
      - key: SEND_USERNAME
        value: "true"
      - key: ENABLE_TTS
        value: "false"
      - key: ENABLE_CHANNEL_POINTS
        value: "false"
      - key: COOLDOWN_DURATION
        value: "10"
